{
	"schema_version": "1.6.0",
	"id": "CVE-2019-3831",
	"modified": "2023-11-29T07:29:34.869362Z",
	"published": "2019-03-25T18:29:00Z",
	"related": [
		"RHBA-2019:1965",
		"RHSA-2019:0457",
		"RHSA-2019:0458"
	],
	"details": "A vulnerability was discovered in vdsm, version 4.19 through 4.30.3 and 4.30.5 through 4.30.8. The systemd_run function exposed to the vdsm system user could be abused to execute arbitrary commands as root.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {},
			"ranges": [
				{
					"type": "GIT",
					"repo": "https://github.com/ovirt/vdsm",
					"events": [
						{
							"introduced": "b4037d1d095540b55bfea2873e3efd1fe4ab75c4"
						}
					]
				}
			],
			"versions": [
				"4.19.49",
				"v4.19.49",
				"v4.19.50",
				"v4.19.51"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-3831.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-3831"
		}
	]
}
